### ISSUE TITLE
From where comes that line?

### ISSUE THREAD

**Issue by gzoritchak** [jnizet/kotlin-multiplatform-gradle-kotlin-dsl-example#1]
https://github.com/jnizet/kotlin-multiplatform-gradle-kotlin-dsl-example/blob/ad43422449551ae9b75674d9f3d50c3c372f6594/buildSrc/build.gradle.kts#L2

It's the first time I see it.

**Comment by jnizet** [comment]
Good question. I took inspiration from https://github.com/gradle/kotlin-dsl/tree/master/samples/project-with-buildSrc.

I'm not absolutely sure of all of what it does. It at least applies a kotlin plugin to enable the compilation of the Kotlin sources in the buildSrc project, and it also adds the gradle API, and I guess some additional Kotlin-specific gradle API, to the compile classpath. 

(Succinct) explanations can be found here: https://github.com/gradle/kotlin-dsl/blob/master/subprojects/plugins/src/main/kotlin/org/gradle/kotlin/dsl/plugins/dsl/KotlinDslPlugin.kt.

**Comment by gzoritchak** [comment]
Some information on that here: https://youtu.be/_yaaCtWF8aE?t=10824
